export const mockCategoriesSheet = [
  { slug: 'sunscreen', name: '선크림', sort_order: '1' },
  { slug: 'toner', name: '토너', sort_order: '2' },
  { slug: 'cream', name: '크림', sort_order: '3' },
  { slug: 'serum', name: '세럼', sort_order: '4' },
  { slug: 'cleansing', name: '클렌징', sort_order: '5' },
  { slug: 'cushion', name: '쿠션', sort_order: '6' },
];

export const mockProductsSheet = [
  {
    product_key: 'PROD_001',
    slug: 'mongdies-excellent-suncream',
    name: '엑설런트 선크림',
    brand: '몽디에스',
    category_slug: 'sunscreen',
    volume_ml: '50',
    image_url: '',
    features: 'SPF50+ PA++++, 무기자차, 피부 저자극',
    skin_types: '건성, 민감성',
    hwahae_url: '',
    official_info_url: '',
    is_active: 'true',
  },
  {
    product_key: 'PROD_002',
    slug: 'fusidyne-zinc-calming-sunscreen',
    name: '더마 트러블 징크 카밍 선크림',
    brand: '후시디움 (동화약품)',
    category_slug: 'sunscreen',
    volume_ml: '50',
    image_url: '',
    features: 'SPF50+ PA++++, 무기자차, 트러블 진정',
    skin_types: '수부지, 지성, 복합성',
    hwahae_url: '',
    official_info_url: '',
    is_active: 'true',
  },
  {
    product_key: 'PROD_003',
    slug: 'starlike-pdrn-skinfit-sunscreen',
    brand: '스타라이크',
    name: '피디알엔 스킨핏 수분 선크림',
    category_slug: 'sunscreen',
    volume_ml: '50',
    image_url: '',
    features: 'SPF50+ PA++++, 유기자차, 물광 에센스 제형',
    skin_types: '수부지, 지성',
    hwahae_url: '',
    official_info_url: '',
    is_active: 'true',
  },
  {
    product_key: 'PROD_004',
    slug: 'arocell-mela-txa-sunserum',
    brand: '아로셀',
    name: '멜라 TXA 선세럼',
    category_slug: 'sunscreen',
    volume_ml: '50',
    image_url: '',
    features: 'SPF50+ PA++++, 유기자차, 미백/주름/자외선 3중',
    skin_types: '건성, 복합성',
    hwahae_url: '',
    official_info_url: '',
    is_active: 'true',
  },
  {
    product_key: 'PROD_005',
    slug: 'innisfree-toneup-nosebum-sunscreen',
    brand: '이니스프리',
    name: '데일리 유브이 톤업 노세범 선크림',
    category_slug: 'sunscreen',
    volume_ml: '50',
    image_url: '',
    features: 'SPF50+ PA++++, 무기자차, 오일컨트롤',
    skin_types: '지성, 복합성, 민감성',
    hwahae_url: '',
    official_info_url: '',
    is_active: 'true',
  },
  {
    product_key: 'PROD_006',
    slug: 'beautyofjoseon-stayfresh-purple',
    brand: '조선미녀',
    name: '스테이 프레쉬 톤업 선크림 퍼플',
    category_slug: 'sunscreen',
    volume_ml: '50',
    image_url: '',
    features: 'SPF50+ PA++++, 혼합자차, 톤 보정',
    skin_types: '건성, 민감성, 복합성',
    hwahae_url: '',
    official_info_url: '',
    is_active: 'true',
  },
  {
    product_key: 'PROD_007',
    slug: 'numbuzin-3-porcelain-toneup',
    brand: '넘버즈인',
    name: '3번 도자기결 톤업베이지 선크림',
    category_slug: 'sunscreen',
    volume_ml: '50',
    image_url: '',
    features: 'SPF50+ PA++++, 혼합자차, 파데프리 톤업',
    skin_types: '민감성, 복합성, 지성, 건성',
    hwahae_url: '',
    official_info_url: '',
    is_active: 'true',
  }
];

export const mockListingsSheet = [
  {
    link_key: 'LINK_COUPANG_1',
    product_key: 'PROD_001',
    seller_code: 'coupang',
    url: 'https://link.coupang.com/a/euTm1IrprU',
    affiliate_url: 'https://link.coupang.com/a/euTm1IrprU',
    store_name: '몽디에스 공식스토어',
    is_official_store: 'true',
    is_rocket: 'true',
    crawl_enabled: 'true',
    crawl_method: 'api',
    is_active: 'true',
  },
  {
    link_key: 'LINK_NAVER_1',
    product_key: 'PROD_001',
    seller_code: 'naver',
    url: 'https://brand.naver.com/mongdies/products/13009860683',
    affiliate_url: '',
    store_name: '몽디에스 공식스토어',
    is_official_store: 'true',
    is_rocket: 'false',
    crawl_enabled: 'true',
    crawl_method: 'api',
    is_active: 'true',
  },
  {
    link_key: 'LINK_COUPANG_2',
    product_key: 'PROD_002',
    seller_code: 'coupang',
    url: 'https://link.coupang.com/a/euTogOeOKi',
    affiliate_url: 'https://link.coupang.com/a/euTogOeOKi',
    store_name: '동화약품 공식몰',
    is_official_store: 'true',
    is_rocket: 'true',
    crawl_enabled: 'true',
    crawl_method: 'api',
    is_active: 'true',
  },
  {
    link_key: 'LINK_NAVER_2',
    product_key: 'PROD_002',
    seller_code: 'naver',
    url: 'https://brand.naver.com/dongwhafusidyne/products/9999261730',
    affiliate_url: '',
    store_name: '동화약품 공식몰',
    is_official_store: 'true',
    is_rocket: 'false',
    crawl_enabled: 'true',
    crawl_method: 'api',
    is_active: 'true',
  },
  {
    link_key: 'LINK_OLIVEYOUNG_3',
    product_key: 'PROD_003',
    seller_code: 'oliveyoung',
    url: 'https://oy.run/g1ip6hEbG0GQsu',
    affiliate_url: 'https://oy.run/g1ip6hEbG0GQsu',
    store_name: '올리브영 공식몰',
    is_official_store: 'true',
    is_rocket: 'false',
    crawl_enabled: 'true',
    crawl_method: 'playwright',
    is_active: 'true',
  },
  {
    link_key: 'LINK_COUPANG_3',
    product_key: 'PROD_003',
    seller_code: 'coupang',
    url: 'https://link.coupang.com/a/euTq778JA4',
    affiliate_url: 'https://link.coupang.com/a/euTq778JA4',
    store_name: '쿠팡 직매입',
    is_official_store: 'false',
    is_rocket: 'true',
    crawl_enabled: 'true',
    crawl_method: 'api',
    is_active: 'true',
  },
  {
    link_key: 'LINK_ZIGZAG_3',
    product_key: 'PROD_003',
    seller_code: 'zigzag',
    url: 'https://s.zigzag.kr/abr/Lx0jJvYi94',
    affiliate_url: 'https://s.zigzag.kr/abr/Lx0jJvYi94',
    store_name: '스타라이크 지그재그스토어',
    is_official_store: 'true',
    is_rocket: 'false',
    crawl_enabled: 'true',
    crawl_method: 'playwright',
    is_active: 'true',
  },
  {
    link_key: 'LINK_ABLY_3',
    product_key: 'PROD_003',
    seller_code: 'ably',
    url: 'https://applink.a-bly.com/ogk2u3',
    affiliate_url: 'https://applink.a-bly.com/ogk2u3',
    store_name: '스타라이크 에이블리스토어',
    is_official_store: 'true',
    is_rocket: 'false',
    crawl_enabled: 'true',
    crawl_method: 'playwright',
    is_active: 'true',
  }
];

export const mockBadgesSheet = [
  {
    product_key: 'PROD_001',
    badge_slug: 'directorpi',
    badge_name: '디렉터파이 추천',
    detail: '2026 무기자차 건성 TOP',
    source_title: '디렉터파이 선크림 큐레이션',
    ref_url: 'https://youtube.com',
    source_date: '2026-06-11',
    is_active: 'true',
  },
  {
    product_key: 'PROD_002',
    badge_slug: 'directorpi',
    badge_name: '디렉터파이 추천',
    detail: '2026 무기자차 지성 TOP',
    source_title: '디렉터파이 선크림 큐레이션',
    ref_url: 'https://youtube.com',
    source_date: '2026-06-11',
    is_active: 'true',
  }
];

export const mockAllowlistSheet = [
  { seller_code: 'naver', brand: '몽디에스', allowed_store_name: '몽디에스 공식스토어', is_active: 'true' },
  { seller_code: 'naver', brand: '동화약품', allowed_store_name: '동화약품 공식몰', is_active: 'true' },
];

export const mockOverridesSheet = [
  { product_key: 'PROD_001', seller_code: 'coupang', override_type: 'price', value: '19800', reason: '쿠팡 파트너스 API 불안정', expires_at: '', is_active: 'true' },
];

export const mockSeoPagesSheet = [
  { slug: 'directorpi-sunscreen', page_type: 'curation', title: '2026 디렉터파이 추천 선크림 TOP 10 최저가 비교', h1: '디렉터파이 추천 선크림 최저가 비교', description: '디렉터파이가 추천한 선크림 중 민감성 피부도 참고하기 좋은 제품을 모아 최저가 기준으로 비교했어요.', category: 'sunscreen', skin_type: '', badge_type: 'directorpi', is_active: 'true' },
];
