/**
 * One-time script: clears old data and writes new simplified format to all Google Sheet tabs,
 * then sets up dropdown data validation for all key columns.
 * Run: npm run sheets:reseed
 */

import { google } from 'googleapis';
import type { sheets_v4 } from 'googleapis';

const ID = process.env.GOOGLE_SHEETS_SPREADSHEET_ID!;

async function getSheets() {
  const creds = JSON.parse(process.env.GOOGLE_SERVICE_ACCOUNT_JSON!);
  const auth  = new google.auth.GoogleAuth({ credentials: creds, scopes: ['https://www.googleapis.com/auth/spreadsheets'] });
  return google.sheets({ version: 'v4', auth });
}

// ─── Headers ─────────────────────────────────────────────────────────────────
// Column order here must match column indices used in setupValidation()
const HEADERS: Record<string, string[]> = {
  categories:         ['slug', 'name', 'sort_order'],
  products:           ['product_key', 'name', 'brand', 'category', 'volume_ml', 'skin_types', 'features', 'hwahae_url', 'image_url', 'is_disabled'],
  product_links:      ['product_name', 'oliveyoung', 'coupang', 'naver', 'zigzag', 'ably'],
  badges:             ['product_name', 'badge_type', 'detail', 'source_title', 'ref_url', 'source_date'],
  retailer_allowlist: ['seller', 'brand', 'allowed_store_name'],
  manual_overrides:   ['product_name', 'seller', 'override_type', 'value', 'reason', 'expires_at'],
  seo_pages:          ['slug', 'page_type', 'title', 'h1', 'description', 'category', 'skin_type', 'badge_type', 'is_active'],
};

// ─── Seed data ────────────────────────────────────────────────────────────────
const CATEGORIES = [
  ['sunscreen', '선크림',  '1'],
  ['toner',     '토너',    '2'],
  ['cream',     '크림',    '3'],
  ['serum',     '세럼',    '4'],
  ['cleansing', '클렌징',  '5'],
  ['cushion',   '쿠션',    '6'],
];

// product_key left blank → auto-generated by import.ts
const PRODUCTS = [
  ['', '엑설런트 선크림',                    '몽디에스',           '선크림', '50', '건성,민감성',            'SPF50+ PA++++, 무기자차, 피부 저자극',          '', '', ''],
  ['', '더마 트러블 징크 카밍 선크림',        '후시다딘 (동화약품)', '선크림', '50', '수부지,지성,복합성',      'SPF50+ PA++++, 무기자차, 트러블 진정',          '', '', ''],
  ['', '피디알엔 스킨핏 수분 선크림',         '스타라이크',          '선크림', '50', '수부지,지성',            'SPF50+ PA++++, 유기자차, 물광 에센스 제형',     '', '', ''],
  ['', '멜라 TXA 선세럼',                    '아로셀',              '선크림', '50', '건성,복합성',            'SPF50+ PA++++, 유기자차, 미백/주름/자외선 3중', '', '', ''],
  ['', '데일리 유브이 톤업 노세범 선크림',    '이니스프리',          '선크림', '50', '지성,복합성,민감성',      'SPF50+ PA++++, 무기자차, 오일컨트롤',          '', '', ''],
  ['', '스테이 프레쉬 톤업 선크림 퍼플',     '조선미녀',            '선크림', '50', '건성,민감성,복합성',      'SPF50+ PA++++, 혼합자차, 톤 보정',             '', '', ''],
  ['', '3번 도자기결 톤업베이지 선크림',      '넘버즈인',            '선크림', '50', '민감성,복합성,지성,건성', 'SPF50+ PA++++, 혼합자차, 파데프리 톤업',       '', '', ''],
];

const PRODUCT_LINKS = [
  ['엑설런트 선크림',                 '',                             'https://link.coupang.com/a/euTm1IrprU',   'https://brand.naver.com/mongdies/products/13009860683',         '',                                   ''                               ],
  ['더마 트러블 징크 카밍 선크림',     '',                             'https://link.coupang.com/a/euTogOeOKi',   'https://brand.naver.com/dongwhafusidyne/products/9999261730',    '',                                   ''                               ],
  ['피디알엔 스킨핏 수분 선크림',      'https://oy.run/g1ip6hEbG0GQsu','https://link.coupang.com/a/euTq778JA4',   '',                                                              'https://s.zigzag.kr/abr/Lx0jJvYi94', 'https://applink.a-bly.com/ogk2u3'],
  ['멜라 TXA 선세럼',                 'https://oy.run/nq6hNFFJuXtQ7h','https://link.coupang.com/a/euTq778JA4',   'https://naver.me/5zURlN5z',                                     'https://s.zigzag.kr/abr/5DvMybQveI', ''                               ],
  ['데일리 유브이 톤업 노세범 선크림', 'https://oy.run/rRbPHHbTfWaDJC','https://link.coupang.com/a/euTvIULPLU',  'https://brand.naver.com/innisfree/products/13155811785',         'https://s.zigzag.kr/abr/FUogL31meU', 'https://applink.a-bly.com/q27718'],
  ['스테이 프레쉬 톤업 선크림 퍼플',  'https://oy.run/gsgwGOxKSzisni','https://link.coupang.com/a/euTyhRQ4LQ',  'https://brand.naver.com/beautyofjoseon/products/13518654945',    '',                                   ''                               ],
  ['3번 도자기결 톤업베이지 선크림',   'https://oy.run/YYKPJc5qEf6uS2','https://link.coupang.com/a/euTAD8gTQW',  'https://brand.naver.com/numbuzin/products/5788327291',           '',                                   ''                               ],
];

const BADGES = [
  ['엑설런트 선크림',                 'directorpi', '2026 무기자차 건성·민감성 Top', '디렉터파이 2026 선크림 추천', '', '2026-06-12'],
  ['더마 트러블 징크 카밍 선크림',     'directorpi', '2026 무기자차 수부지·지성 Top',  '디렉터파이 2026 선크림 추천', '', '2026-06-12'],
  ['피디알엔 스킨핏 수분 선크림',      'directorpi', '2026 유기자차 수부지·지성 Top',  '디렉터파이 2026 선크림 추천', '', '2026-06-12'],
  ['멜라 TXA 선세럼',                 'directorpi', '2026 유기자차 건성·복합성 Top',  '디렉터파이 2026 선크림 추천', '', '2026-06-12'],
  ['데일리 유브이 톤업 노세범 선크림', 'directorpi', '2026 톤업 보송 Top',             '디렉터파이 2026 선크림 추천', '', '2026-06-12'],
  ['스테이 프레쉬 톤업 선크림 퍼플',  'directorpi', '2026 톤업 촉촉 Top',             '디렉터파이 2026 선크림 추천', '', '2026-06-12'],
  ['3번 도자기결 톤업베이지 선크림',   'directorpi', '2026 톤업 파데프리 Top',          '디렉터파이 2026 선크림 추천', '', '2026-06-12'],
];

const ALLOWLIST = [
  ['naver', '몽디에스',   '몽디에스 공식스토어'],
  ['naver', '동화약품',   '동화약품 공식몰'    ],
  ['naver', '이니스프리', '이니스프리 공식몰'  ],
  ['naver', '조선미녀',   '조선미녀 공식몰'    ],
  ['naver', '넘버즈인',   '넘버즈인 공식몰'    ],
];

const SEO_PAGES = [
  ['directorpi-sunscreen',     'curation', '디렉터파이 2026 추천 선크림 TOP 7 최저가 비교',           '디렉터파이 추천 선크림 최저가 비교',   '디렉터파이가 2026년 추천한 선크림 중 무기자차·유기자차·톤업 유형별 TOP 제품을 모아 쿠팡·올리브영·네이버 최저가를 비교했어요.', 'sunscreen', '',     'directorpi', 'true'],
  ['mineral-sunscreen',        'curation', '2026 무기자차 선크림 추천 최저가 비교 | 건성·민감성·지성', '무기자차 선크림 최저가 비교',         '자극 없는 무기자차 선크림을 피부 타입별로 비교했어요.',                                                                            'sunscreen', '',     '',           'true'],
  ['dry-skin-sunscreen',       'skin',     '건성 피부 선크림 추천 최저가 비교 2026',                   '건성 피부 선크림 최저가 비교',        '건성 피부에 맞는 보습력 좋은 선크림을 최저가 기준으로 비교했어요.',                                                                'sunscreen', '건성',  '',           'true'],
  ['sensitive-skin-sunscreen', 'skin',     '민감성 피부 선크림 추천 최저가 비교 2026',                 '민감성 피부 선크림 최저가 비교',      '자극 없는 민감성 피부 선크림을 성분과 가격 기준으로 비교했어요.',                                                                  'sunscreen', '민감성', '',           'true'],
  ['oily-skin-sunscreen',      'skin',     '지성·수부지 피부 선크림 추천 최저가 비교 2026',             '지성·수부지 피부 선크림 최저가 비교', '백탁 없고 오일컨트롤 되는 지성·수부지 선크림을 최저가 기준으로 비교했어요.',                                                         'sunscreen', '지성',  '',           'true'],
  ['toneup-sunscreen',         'curation', '2026 톤업 선크림 추천 최저가 비교 | 보송·촉촉·파데프리',    '톤업 선크림 최저가 비교',            '보송 톤업부터 촉촉 톤업, 파데프리까지 타입별 톤업 선크림을 최저가 기준으로 비교했어요.',                                                  'sunscreen', '',     '',           'true'],
];

// ─── Helpers ─────────────────────────────────────────────────────────────────
type Sheets = Awaited<ReturnType<typeof getSheets>>;
type Request = sheets_v4.Schema$Request;

async function clearAndWriteHeader(sheets: Sheets, tab: string) {
  await sheets.spreadsheets.values.clear({ spreadsheetId: ID, range: `${tab}!A1:Z1000` });
  await sheets.spreadsheets.values.update({
    spreadsheetId: ID, range: `${tab}!A1`,
    valueInputOption: 'RAW', requestBody: { values: [HEADERS[tab]] },
  });
}

async function writeData(sheets: Sheets, tab: string, rows: string[][]) {
  if (!rows.length) return;
  await sheets.spreadsheets.values.update({
    spreadsheetId: ID, range: `${tab}!A2`,
    valueInputOption: 'RAW', requestBody: { values: rows },
  });
}

// ─── Data validation ─────────────────────────────────────────────────────────
// Column indices (0-based) match HEADERS order above:
//   products:      product_key=0, name=1, brand=2, category=3, volume_ml=4,
//                  skin_types=5, features=6, hwahae_url=7, image_url=8, is_disabled=9
//   product_links: product_name=0, oliveyoung=1 ..
//   badges:        product_name=0, badge_type=1 ..
//   allowlist:     seller=0 ..
//   overrides:     product_name=0, seller=1, override_type=2 ..

async function setupValidation(sheets: Sheets) {
  const spreadsheet = await sheets.spreadsheets.get({ spreadsheetId: ID });
  const sheetIds: Record<string, number> = {};
  for (const sheet of spreadsheet.data.sheets ?? []) {
    if (sheet.properties?.title && sheet.properties.sheetId != null) {
      sheetIds[sheet.properties.title] = sheet.properties.sheetId;
    }
  }

  const SELLERS        = ['oliveyoung', 'coupang', 'naver', 'zigzag', 'ably'];
  const BADGE_TYPES    = ['directorpi', 'hwahae_best', 'oliveyoung_best'];
  const OVERRIDE_TYPES = ['price', 'promo_type', 'promo_text', 'unit_price', 'in_stock'];

  // Dropdown from another sheet's column (ONE_OF_RANGE)
  const fromRange = (tab: string, col: number, srcSheet: string, srcCol: string): Request => ({
    setDataValidation: {
      range: { sheetId: sheetIds[tab], startRowIndex: 1, endRowIndex: 1000, startColumnIndex: col, endColumnIndex: col + 1 },
      rule: {
        condition: { type: 'ONE_OF_RANGE', values: [{ userEnteredValue: `='${srcSheet}'!$${srcCol}$2:$${srcCol}$1000` }] },
        strict: false,
        showCustomUi: true,
      },
    },
  });

  // Dropdown from a fixed list (ONE_OF_LIST)
  const fromList = (tab: string, col: number, values: string[], message?: string): Request => ({
    setDataValidation: {
      range: { sheetId: sheetIds[tab], startRowIndex: 1, endRowIndex: 1000, startColumnIndex: col, endColumnIndex: col + 1 },
      rule: {
        condition: { type: 'ONE_OF_LIST', values: values.map((v) => ({ userEnteredValue: v })) },
        inputMessage: message,
        strict: false,
        showCustomUi: true,
      },
    },
  });

  // Input hint only (no dropdown — for free-form fields needing a format hint)
  const withHint = (tab: string, col: number, message: string): Request => ({
    setDataValidation: {
      range: { sheetId: sheetIds[tab], startRowIndex: 1, endRowIndex: 1000, startColumnIndex: col, endColumnIndex: col + 1 },
      rule: {
        condition: { type: 'CUSTOM_FORMULA', values: [{ userEnteredValue: '=TRUE' }] },
        inputMessage: message,
        strict: false,
        showCustomUi: false,
      },
    },
  });

  const requests: Request[] = [
    // products: category(3) ← categories 이름 목록
    fromRange('products', 3, 'categories', 'B'),
    // products: skin_types(5) — 멀티셀렉 미지원, 힌트 메시지만
    withHint('products', 5, '쉼표로 구분하여 입력 (예: 건성,민감성,지성)'),

    // product_links: product_name(0) ← products 이름 목록
    fromRange('product_links', 0, 'products', 'B'),

    // badges: product_name(0) ← products 이름 목록
    fromRange('badges', 0, 'products', 'B'),
    // badges: badge_type(1) ← 고정 목록
    fromList('badges', 1, BADGE_TYPES),

    // retailer_allowlist: seller(0) ← 고정 목록
    fromList('retailer_allowlist', 0, SELLERS),

    // manual_overrides: product_name(0) ← products 이름 목록
    fromRange('manual_overrides', 0, 'products', 'B'),
    // manual_overrides: seller(1) ← 고정 목록
    fromList('manual_overrides', 1, SELLERS),
    // manual_overrides: override_type(2) ← 고정 목록
    fromList('manual_overrides', 2, OVERRIDE_TYPES),
  ];

  await sheets.spreadsheets.batchUpdate({ spreadsheetId: ID, requestBody: { requests } });
  console.log('✓ Data validation dropdowns configured');
}

// ─── Main ─────────────────────────────────────────────────────────────────────
async function reseed() {
  const sheets = await getSheets();

  const tabs: Array<[string, string[][]]> = [
    ['categories',         CATEGORIES   ],
    ['products',           PRODUCTS     ],
    ['product_links',      PRODUCT_LINKS],
    ['badges',             BADGES       ],
    ['retailer_allowlist', ALLOWLIST    ],
    ['manual_overrides',   []           ],
    ['seo_pages',          SEO_PAGES    ],
  ];

  for (const [tab, data] of tabs) {
    await clearAndWriteHeader(sheets, tab);
    await writeData(sheets, tab, data);
    console.log(`✓ ${tab}: header + ${data.length} rows`);
  }

  await setupValidation(sheets);

  console.log('\nDone. Run `npm run sheets:import` to sync to Supabase.');
}

reseed().catch((e) => { console.error(e); process.exit(1); });
