/**
 * One-time script: clears old data and writes new simplified format to all Google Sheet tabs.
 * No dropdown data validation is configured (values are copy-paste friendly).
 * In product_links, `product_name` and `brand` are auto-filled from the `products`
 * tab via ARRAYFORMULA (row-aligned); only the seller-link columns hold data.
 * Run: npm run sheets:reseed
 */

import { google } from 'googleapis';

const ID = process.env.GOOGLE_SHEETS_SPREADSHEET_ID!;

async function getSheets() {
  const creds = JSON.parse(process.env.GOOGLE_SERVICE_ACCOUNT_JSON!);
  const auth  = new google.auth.GoogleAuth({ credentials: creds, scopes: ['https://www.googleapis.com/auth/spreadsheets'] });
  return google.sheets({ version: 'v4', auth });
}

// ─── Headers ─────────────────────────────────────────────────────────────────
const HEADERS: Record<string, string[]> = {
  categories:         ['slug', 'name', 'sort_order'],
  products:           ['product_key', 'name', 'brand', 'category', 'volume_ml', 'skin_types', 'features', 'hwahae_url', 'image_url', 'is_disabled'],
  product_links:      ['product_name', 'brand', 'oliveyoung', 'coupang', 'naver', 'zigzag', 'ably'],
  badges:             ['product_name', 'badge_type', 'detail', 'source_title', 'ref_url', 'source_date'],
  retailer_allowlist: ['seller', 'brand', 'allowed_store_name'],
  manual_overrides:   ['product_name', 'seller', 'override_type', 'value', 'reason', 'expires_at'],
  seo_pages:          ['slug', 'page_type', 'title', 'h1', 'description', 'category', 'skin_type', 'badge_type', 'is_active'],
};

// ─── Seed data ────────────────────────────────────────────────────────────────
const CATEGORIES = [
  ['sunscreen', '선크림',  '1'],
  ['toner',     '토너',    '2'],
  ['cream',     '크림',    '3'],
  ['serum',     '세럼',    '4'],
  ['cleansing', '클렌징',  '5'],
  ['cushion',   '쿠션',    '6'],
];

// product_key left blank → auto-generated by import.ts
const PRODUCTS = [
  ['', '엑설런트 선크림',                    '몽디에스',           '선크림', '50', '건성,민감성',            'SPF50+ PA++++, 무기자차, 피부 저자극',          '', '', ''],
  ['', '더마 트러블 징크 카밍 선크림',        '후시다딘 (동화약품)', '선크림', '50', '수부지,지성,복합성',      'SPF50+ PA++++, 무기자차, 트러블 진정',          '', '', ''],
  ['', '피디알엔 스킨핏 수분 선크림',         '스타라이크',          '선크림', '50', '수부지,지성',            'SPF50+ PA++++, 유기자차, 물광 에센스 제형',     '', '', ''],
  ['', '멜라 TXA 선세럼',                    '아로셀',              '선크림', '50', '건성,복합성',            'SPF50+ PA++++, 유기자차, 미백/주름/자외선 3중', '', '', ''],
  ['', '데일리 유브이 톤업 노세범 선크림',    '이니스프리',          '선크림', '50', '지성,복합성,민감성',      'SPF50+ PA++++, 무기자차, 오일컨트롤',          '', '', ''],
  ['', '스테이 프레쉬 톤업 선크림 퍼플',     '조선미녀',            '선크림', '50', '건성,민감성,복합성',      'SPF50+ PA++++, 혼합자차, 톤 보정',             '', '', ''],
  ['', '3번 도자기결 톤업베이지 선크림',      '넘버즈인',            '선크림', '50', '민감성,복합성,지성,건성', 'SPF50+ PA++++, 혼합자차, 파데프리 톤업',       '', '', ''],
];

// First column is a human-readable label only (NOT written to the sheet).
// product_name & brand are auto-filled from the products tab via ARRAYFORMULA;
// only the seller columns (oliveyoung..ably) are written, to product_links!C2.
// Keep this list in the SAME ORDER as PRODUCTS above — mirroring is by row position.
const PRODUCT_LINKS = [
  ['엑설런트 선크림',                 '',                             'https://link.coupang.com/a/euTm1IrprU',   'https://brand.naver.com/mongdies/products/13009860683',         '',                                   ''                               ],
  ['더마 트러블 징크 카밍 선크림',     '',                             'https://link.coupang.com/a/euTogOeOKi',   'https://brand.naver.com/dongwhafusidyne/products/9999261730',    '',                                   ''                               ],
  ['피디알엔 스킨핏 수분 선크림',      'https://oy.run/g1ip6hEbG0GQsu','https://link.coupang.com/a/euTq778JA4',   '',                                                              'https://s.zigzag.kr/abr/Lx0jJvYi94', 'https://applink.a-bly.com/ogk2u3'],
  ['멜라 TXA 선세럼',                 'https://oy.run/nq6hNFFJuXtQ7h','https://link.coupang.com/a/euTq778JA4',   'https://naver.me/5zURlN5z',                                     'https://s.zigzag.kr/abr/5DvMybQveI', ''                               ],
  ['데일리 유브이 톤업 노세범 선크림', 'https://oy.run/rRbPHHbTfWaDJC','https://link.coupang.com/a/euTvIULPLU',  'https://brand.naver.com/innisfree/products/13155811785',         'https://s.zigzag.kr/abr/FUogL31meU', 'https://applink.a-bly.com/q27718'],
  ['스테이 프레쉬 톤업 선크림 퍼플',  'https://oy.run/gsgwGOxKSzisni','https://link.coupang.com/a/euTyhRQ4LQ',  'https://brand.naver.com/beautyofjoseon/products/13518654945',    '',                                   ''                               ],
  ['3번 도자기결 톤업베이지 선크림',   'https://oy.run/YYKPJc5qEf6uS2','https://link.coupang.com/a/euTAD8gTQW',  'https://brand.naver.com/numbuzin/products/5788327291',           '',                                   ''                               ],
];

const BADGES = [
  ['엑설런트 선크림',                 'directorpi', '2026 무기자차 건성·민감성 Top', '디렉터파이 2026 선크림 추천', '', '2026-06-12'],
  ['더마 트러블 징크 카밍 선크림',     'directorpi', '2026 무기자차 수부지·지성 Top',  '디렉터파이 2026 선크림 추천', '', '2026-06-12'],
  ['피디알엔 스킨핏 수분 선크림',      'directorpi', '2026 유기자차 수부지·지성 Top',  '디렉터파이 2026 선크림 추천', '', '2026-06-12'],
  ['멜라 TXA 선세럼',                 'directorpi', '2026 유기자차 건성·복합성 Top',  '디렉터파이 2026 선크림 추천', '', '2026-06-12'],
  ['데일리 유브이 톤업 노세범 선크림', 'directorpi', '2026 톤업 보송 Top',             '디렉터파이 2026 선크림 추천', '', '2026-06-12'],
  ['스테이 프레쉬 톤업 선크림 퍼플',  'directorpi', '2026 톤업 촉촉 Top',             '디렉터파이 2026 선크림 추천', '', '2026-06-12'],
  ['3번 도자기결 톤업베이지 선크림',   'directorpi', '2026 톤업 파데프리 Top',          '디렉터파이 2026 선크림 추천', '', '2026-06-12'],
];

const ALLOWLIST = [
  ['naver', '몽디에스',   '몽디에스 공식스토어'],
  ['naver', '동화약품',   '동화약품 공식몰'    ],
  ['naver', '이니스프리', '이니스프리 공식몰'  ],
  ['naver', '조선미녀',   '조선미녀 공식몰'    ],
  ['naver', '넘버즈인',   '넘버즈인 공식몰'    ],
];

const SEO_PAGES = [
  ['directorpi-sunscreen',     'curation', '디렉터파이 2026 추천 선크림 TOP 7 최저가 비교',           '디렉터파이 추천 선크림 최저가 비교',   '디렉터파이가 2026년 추천한 선크림 중 무기자차·유기자차·톤업 유형별 TOP 제품을 모아 쿠팡·올리브영·네이버 최저가를 비교했어요.', 'sunscreen', '',     'directorpi', 'true'],
  ['mineral-sunscreen',        'curation', '2026 무기자차 선크림 추천 최저가 비교 | 건성·민감성·지성', '무기자차 선크림 최저가 비교',         '자극 없는 무기자차 선크림을 피부 타입별로 비교했어요.',                                                                            'sunscreen', '',     '',           'true'],
  ['dry-skin-sunscreen',       'skin',     '건성 피부 선크림 추천 최저가 비교 2026',                   '건성 피부 선크림 최저가 비교',        '건성 피부에 맞는 보습력 좋은 선크림을 최저가 기준으로 비교했어요.',                                                                'sunscreen', '건성',  '',           'true'],
  ['sensitive-skin-sunscreen', 'skin',     '민감성 피부 선크림 추천 최저가 비교 2026',                 '민감성 피부 선크림 최저가 비교',      '자극 없는 민감성 피부 선크림을 성분과 가격 기준으로 비교했어요.',                                                                  'sunscreen', '민감성', '',           'true'],
  ['oily-skin-sunscreen',      'skin',     '지성·수부지 피부 선크림 추천 최저가 비교 2026',             '지성·수부지 피부 선크림 최저가 비교', '백탁 없고 오일컨트롤 되는 지성·수부지 선크림을 최저가 기준으로 비교했어요.',                                                         'sunscreen', '지성',  '',           'true'],
  ['toneup-sunscreen',         'curation', '2026 톤업 선크림 추천 최저가 비교 | 보송·촉촉·파데프리',    '톤업 선크림 최저가 비교',            '보송 톤업부터 촉촉 톤업, 파데프리까지 타입별 톤업 선크림을 최저가 기준으로 비교했어요.',                                                  'sunscreen', '',     '',           'true'],
];

// ─── Helpers ─────────────────────────────────────────────────────────────────
type Sheets = Awaited<ReturnType<typeof getSheets>>;

async function clearAndWriteHeader(sheets: Sheets, tab: string) {
  await sheets.spreadsheets.values.clear({ spreadsheetId: ID, range: `${tab}!A1:Z1000` });
  await sheets.spreadsheets.values.update({
    spreadsheetId: ID, range: `${tab}!A1`,
    valueInputOption: 'RAW', requestBody: { values: [HEADERS[tab]] },
  });
}

async function writeData(sheets: Sheets, tab: string, rows: string[][]) {
  if (!rows.length) return;
  await sheets.spreadsheets.values.update({
    spreadsheetId: ID, range: `${tab}!A2`,
    valueInputOption: 'RAW', requestBody: { values: rows },
  });
}

// ─── product_links writer (auto-fill name/brand from products) ────────────────
// product_name (A) & brand (B) mirror the products tab via ARRAYFORMULA, so they
// can never drift from products. Only the seller-link columns (C:G) are written.
async function writeProductLinks(sheets: Sheets, rows: string[][]) {
  const sellerCols = rows.map((r) => r.slice(1)); // drop the readability label → [oliveyoung..ably]
  if (sellerCols.length) {
    await sheets.spreadsheets.values.update({
      spreadsheetId: ID, range: 'product_links!C2',
      valueInputOption: 'RAW', requestBody: { values: sellerCols },
    });
  }
  await sheets.spreadsheets.values.update({
    spreadsheetId: ID, range: 'product_links!A2',
    valueInputOption: 'USER_ENTERED',
    requestBody: {
      values: [[
        '=ARRAYFORMULA(IF(products!B2:B="","",products!B2:B))',
        '=ARRAYFORMULA(IF(products!C2:C="","",products!C2:C))',
      ]],
    },
  });
}

// ─── Main ─────────────────────────────────────────────────────────────────────
async function reseed() {
  const sheets = await getSheets();

  const tabs: Array<[string, string[][]]> = [
    ['categories',         CATEGORIES   ],
    ['products',           PRODUCTS     ],
    ['product_links',      PRODUCT_LINKS],
    ['badges',             BADGES       ],
    ['retailer_allowlist', ALLOWLIST    ],
    ['manual_overrides',   []           ],
    ['seo_pages',          SEO_PAGES    ],
  ];

  for (const [tab, data] of tabs) {
    await clearAndWriteHeader(sheets, tab);
    if (tab === 'product_links') {
      await writeProductLinks(sheets, data);
    } else {
      await writeData(sheets, tab, data);
    }
    console.log(`✓ ${tab}: header + ${data.length} rows`);
  }

  console.log('\nNo dropdowns configured — fields are copy-paste friendly.');
  console.log('product_links: product_name & brand auto-fill from the products tab.');
  console.log('\nDone. Run `npm run sheets:import` to sync to Supabase.');
}

reseed().catch((e) => { console.error(e); process.exit(1); });
